name: 🚀 Validation Pipeline
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [middleware]
  pull_request:
    branches: [middleware]
permissions:
  actions: write
  contents: read
  # Required to put a comment into the pull-request
  pull-requests: write
jobs:
  lint:
    name: ⬣ Biome lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
     - uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2
     - run: biome ci . --reporter=github

  typecheck:
    needs: lint
    name: 🔎 Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run typegen
      - run: pnpm run typecheck
      - run: pnpm run check:unused
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm run test:cov
      - name: "Report Coverage"
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@adec81c7327940e0578d70d0bbdd87b0ca21df55 # v2
      - name: Deploy
        if: github.event_name != 'pull_request' && github.ref_name == 'middleware'
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
